// movies
export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE';
export const REMOVE_FAVORITE_MOVIE = 'REMOVE_FAVORITE_MOVIE';
export const FETCH_FAVORITE_MOVIES = 'FETCH_FAVORITE_MOVIES';
export const UPDATE_MOVIES_LIST = 'UPDATE_MOVIES_LIST';
export const REFRESH_MOVIES_STORE = 'REFRESH_MOVIES_STORE';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';

// auth
export const SAVE_AUTHENTICATED_USER = 'SAVE_AUTHENTICATED_USER';
export const SAVE_AUTHENTICATION_ERROR = 'SAVE_AUTHENTICATION_ERROR';
export const REMOVE_AUTHENTICATION_ERROR = 'REMOVE_AUTHENTICATION_ERROR';
export const TOGGLE_SUBMITTING_STATUS = 'TOGGLE_SUBMITTING_STATUS';
export const LOGOUT_USER = 'LOGOUT_USER';
